### PR TITLE
Zombie hit playerfeedback

### LINKED ISSUE #31: Zombie hit playerfeedback
Some kind of feedback when the zombie gets hit. Perhaps the zombie flickers momentarily

### PR DESCRIPTION
**Pull request by Wardergrip**
Resolves #31 

For some reason it still feels quite underwhelming. Any suggestions of what might be better?

Flicker

### CODE REVIEW

**Review by AtlantiaKing — COMMENTED** [review]
Maybe experiment with different flash colors, e.g. red?
Maybe try adding a blood particle?

Ultimate polish: blood splat on the ground everytime a zombie gets hits.

**Comment by Wardergrip** [comment]
Changing it to red does indeed look better. Will experiment with particles

Flicker

**Comment by Wardergrip** [comment]
Added particles

Particles

**Review by AtlantiaKing — APPROVED** [review]
Just remove the commented code in MaterialFlicker.cs

**Pull request merged**
